spring:
  datasource:
    url: jdbc:mysql://localhost:3306/free_courese?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112233

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create